# Server settings
server:
    port: 8080
    address: localhost


# SPRING PROFILES
spring:
    # DATASOURCE
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&charaterEncoding=utf-8
        username: root
        password: Vinsen1991
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        dbcp2:
            initial-size: 5
            min-idle: 5
            max-idle: 20
            max-wait-millis: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            pool-prepared-statements: true
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false



    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.force: true
        encoding.enabled: true

    # close the default cache
    thymeleaf:
        cache: false



# LOGGING
logging:
    level: com.ibatis:DEBUG
